version: 0.0.0.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\Projects\DarkTests

platform: x86
configuration: Release

install:
  - cmd: cinst cmake -version 3.2.3 -y
  - cmd: cmake --version
  # by default, all script lines are interpreted as batch

build:
  project: c:\Projects\DarkTests\build\DarkTests.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running DarkTests_VS2013_SLN.bat...
  - cd c:\Projects\DarkTests
  - DarkTests_VS2013_SLN.bat

# scripts to run after build
after_build:
  - cd C:\Projects\DarkTests
  - cd C:\Projects\DarkTests\build\Release\

artifacts:
  - path: DarkTests.exe
    name: DarkTests.exe